-- =============================================================================
-- Migration: 20260716109_analytics_policies.sql
-- Phase:     3.2 — Enterprise Row Level Security
-- Purpose:   RLS for Analytics & KPI Engine.
--            kpi_definitions, kpi_snapshots, dashboard_snapshots,
--            *_metrics, *_analytics
-- =============================================================================

-- =============================================================================
-- KPI DEFINITIONS & SNAPSHOTS
-- =============================================================================
DROP POLICY IF EXISTS "kpi_def_select" ON public.kpi_definitions;
CREATE POLICY "kpi_def_select" ON public.kpi_definitions FOR SELECT USING (true);
DROP POLICY IF EXISTS "kpi_def_write" ON public.kpi_definitions;
CREATE POLICY "kpi_def_write" ON public.kpi_definitions FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "kpi_snap_select" ON public.kpi_snapshots;
CREATE POLICY "kpi_snap_select" ON public.kpi_snapshots FOR SELECT USING (
  public.fn_is_platform_admin()
  OR org_id = public.fn_jwt_org_id()
  OR vendor_id = public.fn_jwt_vendor_id()
  OR technician_id = public.fn_jwt_tech_id()
);
-- Snapshots are generated by Edge Functions (service_role)
DROP POLICY IF EXISTS "kpi_snap_write" ON public.kpi_snapshots;
CREATE POLICY "kpi_snap_write" ON public.kpi_snapshots FOR ALL USING (public.fn_is_platform_admin());

-- =============================================================================
-- DASHBOARDS
-- =============================================================================
DROP POLICY IF EXISTS "dashboard_snap_select" ON public.dashboard_snapshots;
CREATE POLICY "dashboard_snap_select" ON public.dashboard_snapshots FOR SELECT USING (
  public.fn_is_platform_admin()
  OR (dashboard_type = 'organization' AND entity_id = public.fn_jwt_org_id())
  OR (dashboard_type = 'vendor' AND entity_id = public.fn_jwt_vendor_id())
  OR (dashboard_type = 'technician' AND entity_id = public.fn_jwt_tech_id())
);
DROP POLICY IF EXISTS "dashboard_snap_write" ON public.dashboard_snapshots;
CREATE POLICY "dashboard_snap_write" ON public.dashboard_snapshots FOR ALL USING (public.fn_is_platform_admin());

-- =============================================================================
-- PERFORMANCE METRICS & ANALYTICS (Read-only for users, populated by Edge Func)
-- =============================================================================
DROP POLICY IF EXISTS "vendor_perf_select" ON public.vendor_performance_metrics;
CREATE POLICY "vendor_perf_select" ON public.vendor_performance_metrics FOR SELECT USING (
  public.fn_is_platform_admin() OR org_id = public.fn_jwt_org_id() OR vendor_id = public.fn_jwt_vendor_id()
);
DROP POLICY IF EXISTS "vendor_perf_write" ON public.vendor_performance_metrics;
CREATE POLICY "vendor_perf_write" ON public.vendor_performance_metrics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "tech_perf_select" ON public.technician_performance_metrics;
CREATE POLICY "tech_perf_select" ON public.technician_performance_metrics FOR SELECT USING (
  public.fn_is_platform_admin() OR vendor_id = public.fn_jwt_vendor_id() OR technician_id = public.fn_jwt_tech_id()
);
DROP POLICY IF EXISTS "tech_perf_write" ON public.technician_performance_metrics;
CREATE POLICY "tech_perf_write" ON public.technician_performance_metrics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "asset_analytics_select" ON public.asset_analytics;
CREATE POLICY "asset_analytics_select" ON public.asset_analytics FOR SELECT USING (
  public.fn_is_platform_admin() OR org_id = public.fn_jwt_org_id()
);
DROP POLICY IF EXISTS "asset_analytics_write" ON public.asset_analytics;
CREATE POLICY "asset_analytics_write" ON public.asset_analytics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "sla_analytics_select" ON public.sla_analytics;
CREATE POLICY "sla_analytics_select" ON public.sla_analytics FOR SELECT USING (
  public.fn_is_platform_admin() OR org_id = public.fn_jwt_org_id() OR vendor_id = public.fn_jwt_vendor_id()
);
DROP POLICY IF EXISTS "sla_analytics_write" ON public.sla_analytics;
CREATE POLICY "sla_analytics_write" ON public.sla_analytics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "ai_analytics_select" ON public.ai_analytics;
CREATE POLICY "ai_analytics_select" ON public.ai_analytics FOR SELECT USING (
  public.fn_is_platform_admin() OR org_id = public.fn_jwt_org_id() OR vendor_id = public.fn_jwt_vendor_id()
);
DROP POLICY IF EXISTS "ai_analytics_write" ON public.ai_analytics;
CREATE POLICY "ai_analytics_write" ON public.ai_analytics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "revenue_analytics_select" ON public.revenue_analytics;
CREATE POLICY "revenue_analytics_select" ON public.revenue_analytics FOR SELECT USING (
  public.fn_is_platform_admin() OR org_id = public.fn_jwt_org_id() OR vendor_id = public.fn_jwt_vendor_id()
);
DROP POLICY IF EXISTS "revenue_analytics_write" ON public.revenue_analytics;
CREATE POLICY "revenue_analytics_write" ON public.revenue_analytics FOR ALL USING (public.fn_is_platform_admin());

DROP POLICY IF EXISTS "platform_analytics_select" ON public.platform_analytics;
CREATE POLICY "platform_analytics_select" ON public.platform_analytics FOR SELECT USING (public.fn_is_platform_admin());
DROP POLICY IF EXISTS "platform_analytics_write" ON public.platform_analytics;
CREATE POLICY "platform_analytics_write" ON public.platform_analytics FOR ALL USING (public.fn_is_platform_admin());
