-- =============================================================================
-- Migration: 20260716049_pm_schedules.sql
-- Phase:     2.3 — Enterprise PM, AMC, & Warranty Engine
-- Purpose:   Create the `pm_schedules` table.
--            Instantiated calendar events generated from a PM Plan.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.pm_schedules (
  id                       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- ── Linkage ───────────────────────────────────────────────────────────────
  pm_plan_id               UUID          NOT NULL
                             REFERENCES public.pm_plans (id)
                             ON DELETE CASCADE,

  -- ── Calendar Event ────────────────────────────────────────────────────────
  scheduled_date           DATE          NOT NULL,
  scheduled_start_at       TIMESTAMPTZ,
  scheduled_end_at         TIMESTAMPTZ,

  status                   public.pm_status NOT NULL DEFAULT 'requested',

  -- ── Execution Artifacts ───────────────────────────────────────────────────
  -- When the time comes, the system generates a ticket/WO for execution
  generated_ticket_id      UUID          REFERENCES public.tickets (id) ON DELETE SET NULL,
  generated_work_order_id  UUID          REFERENCES public.work_orders (id) ON DELETE SET NULL,

  -- ── Resolution ────────────────────────────────────────────────────────────
  completed_at             TIMESTAMPTZ,
  missed_at                TIMESTAMPTZ,
  skipped_reason           TEXT,

  -- ── Audit Fields ──────────────────────────────────────────────────────────
  created_by               UUID          REFERENCES public.profiles (id) ON DELETE SET NULL,
  updated_by               UUID          REFERENCES public.profiles (id) ON DELETE SET NULL,
  deleted_at               TIMESTAMPTZ   DEFAULT NULL,
  created_at               TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_pm_schedules_plan_id
  ON public.pm_schedules (pm_plan_id);

CREATE INDEX IF NOT EXISTS idx_pm_schedules_date
  ON public.pm_schedules (scheduled_date)
  WHERE deleted_at IS NULL;

-- ── updated_at Trigger ────────────────────────────────────────────────────────
CREATE TRIGGER trg_pm_schedules_updated_at
  BEFORE UPDATE ON public.pm_schedules
  FOR EACH ROW EXECUTE FUNCTION public.fn_set_updated_at();

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE  public.pm_schedules IS 'Specific calendar occurrences generated by a PM Plan.';
